akademia_homepage:
    path:     /
    defaults: { _controller: AkademiaBundle:Default:index }
    methods:  [GET,POST]


akademia_registrar:
    path:     /registrar
    defaults: { _controller: AkademiaBundle:Default:registrar }
    methods:  [GET,POST]


akademia_getPost:
    path:     /post/get
    defaults: { _controller: AkademiaBundle:Default:post}
    methods:  [GET,POST]


