akademia_homepage:
    path:     /
    defaults: { _controller: AkademiaBundle:Default:index }
    methods:  [GET,POST]

akademia_registrar:
    path:     /registrar
    defaults: { _controller: AkademiaBundle:Default:registrar }
    methods:  [GET,POST]

akademia_mostrarficha:
    path:     /mostrarficha
    defaults: { _controller: AkademiaBundle:Default:mostrarficha }
    methods:  [GET,POST]

akademia_getPost:
    path:     /post/get
    defaults: { _controller: AkademiaBundle:Default:post}
    methods:  [GET,POST]

akademia_sendemailapoderado:
    path:     /sendemailapoderado
    defaults: { _controller: AkademiaBundle:Default:sendemailapoderado}
    methods:  [GET,POST]

akademia_generarPdfInscripcion:
    path:     /pdf/inscripcion/{id}
    defaults: { _controller: AkademiaBundle:Default:generarPdfInscripcion}
    methods:  [GET,POST]

akademia_generarPdfDeclaracionJurada:
    path:     /pdf/declaracion-jurada/{id}
    defaults: { _controller: AkademiaBundle:Default:generarPdfDeclaracionJurada}
    methods:  [GET,POST]

akademia_sendemail:
    path:     /sendemail
    defaults: { _controller: AkademiaBundle:Default:sendemail}
    methods:  [GET,POST]

akademia_prueba:
    path:     /prueba
    defaults: { _controller: AkademiaBundle:Default:prueba}
    methods:  [GET,POST]


akademia_sendemailusuario:
    path:     /sendemailusuario
    defaults: { _controller: AkademiaBundle:Default:sendemailusuario}
    methods:  [GET,POST]

akademia_consulta:
    path:     /consulta
    defaults: { _controller: AkademiaBundle:Default:consulta}
    methods:  [GET,POST]

akademia_mostrarcomplejos:
    path:    /mostrarcomplejos
    defaults: {_controller: AkademiaBundle:Default:mostrarcomplejos}
    methods: [GET,POST]

akademia_inscritos:
    path:    /inscritos
    defaults: {_controller: AkademiaBundle:Default:inscritos}
    methods: [GET,POST]

akademia_cambiarestado:
    path:   /cambiarestado
    defaults: {_controller: AkademiaBundle:Default:cambiarestado}
    methods: [GET, POST]


akademia_login:
    path:    /login
    defaults: {_controller: AkademiaBundle:Default:login}

akademia_login_check:
    path:    /login_check

akademia_logout:
    path:    /logout

